### ISSUE TITLE
Constitution Improvements meta-issue 119: members on co-op

### ISSUE THREAD

**Issue by fboxwala** [wics-uw/website#124]
In my experience, members on co-op can be effective. Akshaya did quite well as Big Csters director.

I would say office manager, sys-admin, chair and secretary should be on a study term.

@wics-uw/contributors

**Comment by evykassirer** [comment]
honestly, MX was on coop as a CS145 ISA and she's been in the office tons, and seems to have more time than any of the rest of us

**Comment by fboxwala** [comment]
I think ISA's are a special case. Anna was off-campus cooping so it was really hard for her to be in the office during hours. We could change the wording to:

Office manager and sys-admin must be either studying or working _on campus_
Chair and Secretary should be on a _study term_

**Comment by evykassirer** [comment]
yesss ++

**Comment by ehashman** [comment]
I might want to word this slightly differently because co-op students taking one class are considered to be on a part-time study term/studying (and trust me, from past experience, in that case you have the _least_ time for extracurrics).

I don't want to exclude students who are taking a reduced courseload and don't qualify as full-time, so maybe we could write it "on a study term with no competing full-time commitments (such as a co-op job)"?

**Comment by fboxwala** [comment]
Office manager and sys-admin must be either studying or working _on campus_
Chair and Secretary should be on a _study term with no competeing full-time commitments (such as a co-op job)_

^?

**Comment by ehashman** [comment]
+1 Fatema

Just wanted to also make sure we're not missing any cases... the remaining 3 positions are Big CSters director, finance director, and marketing/publicity. I wonder if the finance director should be allowed to be on co-op, or at least off-campus... there are a number of financial meetings that need to happen during business hours, so it could be problematic if the finance director can't attend them?

**Comment by fboxwala** [comment]
+1 to Finance being on campus

**Comment by ehashman** [comment]
Resolved by #136
